#!/bin/bash

# Disable waveform dumping
OMSP_NODUMP=1
export OMSP_NODUMP

# Choose GCC toolchain prefix ('msp430' for MSPGCC / 'msp430-elf' for GCC RedHat/TI)
# Note: default to MSPGCC until GCC RedHat/TI is mature enough
if command -v msp430-gcc >/dev/null; then
    MSPGCC_PFX=msp430
else
    MSPGCC_PFX=msp430-elf
fi
#MSPGCC_PFX=msp430
export MSPGCC_PFX

# Choose simulator:
#                   - iverilog  : Icarus Verilog  (default)
#                   - cver      : CVer
#                   - verilog   : Verilog-XL
#                   - ncverilog : NC-Verilog
#                   - vcs       : VCS
#                   - vsim      : Modelsim
#                   - isim      : Xilinx simulator
OMSP_SIMULATOR=ncverilog
export OMSP_SIMULATOR


# Argument specifies number of regression loops
if [ $# -ne 1 ]; then
    LAST_REGRESSION=0
else
    LAST_REGRESSION=$(($1-1))
fi

# Cleanup from previous regression
LOG_DIR=./log
rm -rf $LOG_DIR/*

# Perform the regression runs
for (( ii=0; ii<=$LAST_REGRESSION; ii++ ))
  do

    # Cleanup & log directory setup
    rm -rf ./cov_work
    LOG_DIR=./log/$ii
    mkdir -p $LOG_DIR
     
    # Two-Operand Arithmetic test patterns
    ../bin/msp430sim two-op_mov               2>&1 | tee $LOG_DIR/two-op_mov.log
    ../bin/msp430sim two-op_mov-b             2>&1 | tee $LOG_DIR/two-op_mov-b.log
    ../bin/msp430sim two-op_add               2>&1 | tee $LOG_DIR/two-op_add.log

    ../bin/msp430sim two-op_add-b             2>&1 | tee $LOG_DIR/two-op_add-b.log
    ../bin/msp430sim two-op_addc              2>&1 | tee $LOG_DIR/two-op_addc.log
    ../bin/msp430sim two-op_sub               2>&1 | tee $LOG_DIR/two-op_sub.log
    ../bin/msp430sim two-op_subc              2>&1 | tee $LOG_DIR/two-op_subc.log
    ../bin/msp430sim two-op_cmp               2>&1 | tee $LOG_DIR/two-op_cmp.log
    ../bin/msp430sim two-op_bit               2>&1 | tee $LOG_DIR/two-op_bit.log
    ../bin/msp430sim two-op_bic               2>&1 | tee $LOG_DIR/two-op_bic.log
    ../bin/msp430sim two-op_bis               2>&1 | tee $LOG_DIR/two-op_bis.log
    ../bin/msp430sim two-op_xor               2>&1 | tee $LOG_DIR/two-op_xor.log
    ../bin/msp430sim two-op_and               2>&1 | tee $LOG_DIR/two-op_and.log
    ../bin/msp430sim two-op_dadd              2>&1 | tee $LOG_DIR/two-op_dadd.log
    ../bin/msp430sim two-op_autoincr          2>&1 | tee $LOG_DIR/two-op_autoincr.log
    ../bin/msp430sim two-op_autoincr-b        2>&1 | tee $LOG_DIR/two-op_autoincr-b.log
     
    # Conditional Jump test patterns
    ../bin/msp430sim c-jump_jeq               2>&1 | tee $LOG_DIR/c-jump_jeq.log
    ../bin/msp430sim c-jump_jne               2>&1 | tee $LOG_DIR/c-jump_jne.log
    ../bin/msp430sim c-jump_jc                2>&1 | tee $LOG_DIR/c-jump_jc.log
    ../bin/msp430sim c-jump_jnc               2>&1 | tee $LOG_DIR/c-jump_jnc.log
    ../bin/msp430sim c-jump_jn                2>&1 | tee $LOG_DIR/c-jump_jn.log
    ../bin/msp430sim c-jump_jge               2>&1 | tee $LOG_DIR/c-jump_jge.log
    ../bin/msp430sim c-jump_jl                2>&1 | tee $LOG_DIR/c-jump_jl.log
    ../bin/msp430sim c-jump_jmp               2>&1 | tee $LOG_DIR/c-jump_jmp.log
     
    # Single-Operand Arithmetic test patterns
    ../bin/msp430sim sing-op_rrc              2>&1 | tee $LOG_DIR/sing-op_rrc.log
    ../bin/msp430sim sing-op_rra              2>&1 | tee $LOG_DIR/sing-op_rra.log
    ../bin/msp430sim sing-op_swpb             2>&1 | tee $LOG_DIR/sing-op_swpb.log
    ../bin/msp430sim sing-op_sxt              2>&1 | tee $LOG_DIR/sing-op_sxt.log
    ../bin/msp430sim sing-op_push             2>&1 | tee $LOG_DIR/sing-op_push.log
    ../bin/msp430sim sing-op_call             2>&1 | tee $LOG_DIR/sing-op_call.log
     
    # Interrupts & NMI
    ../bin/msp430sim sing-op_reti             2>&1 | tee $LOG_DIR/sing-op_reti.log
    ../bin/msp430sim nmi                      2>&1 | tee $LOG_DIR/nmi.log
    ../bin/msp430sim irq32                    2>&1 | tee $LOG_DIR/irq32.log
    ../bin/msp430sim irq64                    2>&1 | tee $LOG_DIR/irq64.log
     
    # ROM Data Read access
    ../bin/msp430sim two-op_add_rom-rd        2>&1 | tee $LOG_DIR/two-op_add_rom-rd.log
    ../bin/msp430sim sing-op_push_rom-rd      2>&1 | tee $LOG_DIR/sing-op_push_rom-rd.log
    ../bin/msp430sim sing-op_call_rom-rd      2>&1 | tee $LOG_DIR/sing-op_call_rom-rd.log
     
    # Power saving modes (CPUOFF, OSCOFF, SCG0, SCG1)
    ../bin/msp430sim op_modes                 2>&1 | tee $LOG_DIR/op_modes.log
    ../bin/msp430sim op_modes_asic            2>&1 | tee $LOG_DIR/op_modes_asic.log
    ../bin/msp430sim lp_modes_asic            2>&1 | tee $LOG_DIR/lp_modes_asic.log
    ../bin/msp430sim lp_modes_dbg_asic        2>&1 | tee $LOG_DIR/lp_modes_dbg_asic.log
     
    # CPU startup conditions
    ../bin/msp430sim cpu_startup_asic         2>&1 | tee $LOG_DIR/cpu_startup_asic.log
     
    # Basic clock module
    ../bin/msp430sim clock_module             2>&1 | tee $LOG_DIR/clock_module.log
    ../bin/msp430sim clock_module_asic        2>&1 | tee $LOG_DIR/clock_module_asic.log
    ../bin/msp430sim clock_module_asic_mclk   2>&1 | tee $LOG_DIR/clock_module_asic_mclk.log
    ../bin/msp430sim clock_module_asic_smclk  2>&1 | tee $LOG_DIR/clock_module_asic_smclk.log
    ../bin/msp430sim clock_module_asic_lfxt   2>&1 | tee $LOG_DIR/clock_module_asic_lfxt.log
     
    # Serial Debug Interface (UART)
    ../bin/msp430sim dbg_uart                 2>&1 | tee $LOG_DIR/dbg_uart.log
    ../bin/msp430sim dbg_uart_sync            2>&1 | tee $LOG_DIR/dbg_uart_sync.log
    ../bin/msp430sim dbg_uart_cpu             2>&1 | tee $LOG_DIR/dbg_uart_cpu.log
    ../bin/msp430sim dbg_uart_mem             2>&1 | tee $LOG_DIR/dbg_uart_mem.log
    ../bin/msp430sim dbg_uart_hwbrk0          2>&1 | tee $LOG_DIR/dbg_uart_hwbrk0.log
    ../bin/msp430sim dbg_uart_hwbrk1          2>&1 | tee $LOG_DIR/dbg_uart_hwbrk1.log
    ../bin/msp430sim dbg_uart_hwbrk2          2>&1 | tee $LOG_DIR/dbg_uart_hwbrk2.log
    ../bin/msp430sim dbg_uart_hwbrk3          2>&1 | tee $LOG_DIR/dbg_uart_hwbrk3.log
    ../bin/msp430sim dbg_uart_rdwr            2>&1 | tee $LOG_DIR/dbg_uart_rdwr.log
    ../bin/msp430sim dbg_uart_halt_irq        2>&1 | tee $LOG_DIR/dbg_uart_halt_irq.log
    ../bin/msp430sim dbg_uart_onoff           2>&1 | tee $LOG_DIR/dbg_uart_onoff.log
    ../bin/msp430sim dbg_uart_onoff_asic      2>&1 | tee $LOG_DIR/dbg_uart_onoff_asic.log
     
    # Serial Debug Interface (I2C)
    ../bin/msp430sim dbg_i2c                  2>&1 | tee $LOG_DIR/dbg_i2c.log
    ../bin/msp430sim dbg_i2c_sync             2>&1 | tee $LOG_DIR/dbg_i2c_sync.log
    ../bin/msp430sim dbg_i2c_cpu              2>&1 | tee $LOG_DIR/dbg_i2c_cpu.log
    ../bin/msp430sim dbg_i2c_mem              2>&1 | tee $LOG_DIR/dbg_i2c_mem.log
    ../bin/msp430sim dbg_i2c_hwbrk0           2>&1 | tee $LOG_DIR/dbg_i2c_hwbrk0.log
    ../bin/msp430sim dbg_i2c_hwbrk1           2>&1 | tee $LOG_DIR/dbg_i2c_hwbrk1.log
    ../bin/msp430sim dbg_i2c_hwbrk2           2>&1 | tee $LOG_DIR/dbg_i2c_hwbrk2.log
    ../bin/msp430sim dbg_i2c_hwbrk3           2>&1 | tee $LOG_DIR/dbg_i2c_hwbrk3.log
    ../bin/msp430sim dbg_i2c_rdwr             2>&1 | tee $LOG_DIR/dbg_i2c_rdwr.log
    ../bin/msp430sim dbg_i2c_halt_irq         2>&1 | tee $LOG_DIR/dbg_i2c_halt_irq.log
    ../bin/msp430sim dbg_i2c_onoff            2>&1 | tee $LOG_DIR/dbg_i2c_onoff.log
    ../bin/msp430sim dbg_i2c_onoff_asic       2>&1 | tee $LOG_DIR/dbg_i2c_onoff_asic.log
     
    # SFR test patterns
    ../bin/msp430sim sfr                      2>&1 | tee $LOG_DIR/sfr.log
     
    # SCAN test patterns (only to increase coverage)
    ../bin/msp430sim scan                     2>&1 | tee $LOG_DIR/scan.log
     
    # Watchdog test patterns
    ../bin/msp430sim wdt_interval             2>&1 | tee $LOG_DIR/wdt_interval.log
    ../bin/msp430sim wdt_watchdog             2>&1 | tee $LOG_DIR/wdt_watchdog.log
    ../bin/msp430sim wdt_clkmux               2>&1 | tee $LOG_DIR/wdt_clkmux.log
    ../bin/msp430sim wdt_wkup                 2>&1 | tee $LOG_DIR/wdt_wkup.log
     
    # GPIO test patterns
    ../bin/msp430sim gpio_rdwr                2>&1 | tee $LOG_DIR/gpio_rdwr.log
    ../bin/msp430sim gpio_irq                 2>&1 | tee $LOG_DIR/gpio_irq.log
     
    # Peripheral templates test patterns
    ../bin/msp430sim template_periph_8b       2>&1 | tee $LOG_DIR/template_periph_8b.log
    ../bin/msp430sim template_periph_16b      2>&1 | tee $LOG_DIR/template_periph_16b.log
     
    # Timer A patterns
    ../bin/msp430sim tA_modes                 2>&1 | tee $LOG_DIR/tA_modes.log
    ../bin/msp430sim tA_compare               2>&1 | tee $LOG_DIR/tA_compare.log
    ../bin/msp430sim tA_output                2>&1 | tee $LOG_DIR/tA_output.log
    ../bin/msp430sim tA_capture               2>&1 | tee $LOG_DIR/tA_capture.log
    ../bin/msp430sim tA_clkmux                2>&1 | tee $LOG_DIR/tA_clkmux.log
     
    # DMA Interface
    ../bin/msp430sim dma_rdwr_16b             2>&1 | tee $LOG_DIR/dma_rdwr_16b.log
    ../bin/msp430sim dma_rdwr_8b              2>&1 | tee $LOG_DIR/dma_rdwr_8b.log
    ../bin/msp430sim dma_resp                 2>&1 | tee $LOG_DIR/dma_resp.log
    ../bin/msp430sim dma_dbg_arbiter          2>&1 | tee $LOG_DIR/dma_dbg_arbiter.log
    ../bin/msp430sim dma_lpm0_asic            2>&1 | tee $LOG_DIR/dma_lpm0_asic.log
    ../bin/msp430sim dma_lpm1_asic            2>&1 | tee $LOG_DIR/dma_lpm1_asic.log
    ../bin/msp430sim dma_lpm2_asic            2>&1 | tee $LOG_DIR/dma_lpm2_asic.log
    ../bin/msp430sim dma_lpm3_asic            2>&1 | tee $LOG_DIR/dma_lpm3_asic.log
    ../bin/msp430sim dma_lpm4_asic            2>&1 | tee $LOG_DIR/dma_lpm4_asic.log

    # Simple full duplex UART (8N1 protocol)
    #../bin/msp430sim uart                    2>&1 | tee $LOG_DIR/uart.log
     
    # Hardware multiplier test patterns
    ../bin/msp430sim mpy_basic                2>&1 | tee $LOG_DIR/mpy_basic.log
     
     
    # Report regression results
    ../bin/parse_results $LOG_DIR             2>&1 | tee $LOG_DIR/../summary.$ii.log

done


if [ $LAST_REGRESSION != 0 ]; then
    ../bin/parse_summaries                    2>&1 | tee $LOG_DIR/../regressions_summary.log
fi
